version: '3.3'

services:
    www:
        image: stanfordnmbl/gaitlab
        ports:
          - "80:80"
        env_file:
          - ".env"
        depends_on:
          - redis
        volumes:
          - ./data:/code/data
    redis:
        image: redis
        ports:
          - "6379:6379"
