# Generated by Django 3.0.8 on 2020-07-13 05:19

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('response', jsonfield.fields.JSONField(default=dict)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='submitted', max_length=10)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaitlab.Video')),
            ],
        ),
    ]
