# Generated by Django 3.0.8 on 2020-07-14 04:17

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gaitlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=8, max_length=8, unique=True),
        ),
    ]
