# Generated by Django 3.0.8 on 2020-07-14 04:28

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gaitlab', '0002_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='response',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
